# Generated by Django 4.2 on 2023-05-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Tipo de Usuario'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='short_name',
            field=models.CharField(max_length=2, verbose_name='Sigla'),
        ),
    ]
