# Generated by Django 4.2 on 2023-05-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='descuento',
            field=models.TextField(null=True, verbose_name='Codigo de descuento'),
        ),
    ]
