# Generated by Django 4.2 on 2023-05-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_colaboradores_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='descuento',
            field=models.CharField(max_length=100, null=True, verbose_name='Codigo de descuento'),
        ),
    ]
