# Generated by Django 4.2 on 2023-06-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_alter_colaboradores_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='url',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/colab/', max_length=350, null=True, verbose_name='Enlace'),
        ),
    ]
