# Generated by Django 4.2 on 2023-05-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='servicios',
            field=models.ManyToManyField(to='perfil.tservicio', verbose_name='Tipos de servicios'),
        ),
    ]
