# Generated by Django 4.2 on 2023-05-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='categoria',
        ),
        migrations.AddField(
            model_name='user',
            name='tipodeusuario',
            field=models.CharField(blank=True, choices=[('CL', 'Cliente'), ('CU', 'Cuidador')], max_length=2),
        ),
    ]
