# Generated by Django 4.2 on 2023-05-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.IntegerField(blank=True, max_length=9),
        ),
    ]
