# Generated by Django 4.2 on 2023-05-17 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_alter_categoria_name_alter_categoria_short_name'),
        ('users', '0009_alter_user_rut_alter_user_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria'),
        ),
    ]
