# Generated by Django 4.2 on 2023-05-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_apellidos_alter_user_nombres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.PositiveIntegerField(max_length=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.PositiveIntegerField(max_length=9),
        ),
    ]
