# Generated by Django 4.2 on 2023-05-21 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_alter_categoria_name_alter_categoria_short_name'),
        ('users', '0015_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='categoria',
            field=models.ForeignKey(default='Seleccione tipo de usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria'),
        ),
    ]
