# Generated by Django 4.2 on 2023-05-23 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tservicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Tipo de servicio')),
            ],
            options={
                'verbose_name': 'Tipo de servicio',
                'verbose_name_plural': 'Tipos de servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='user_images/image_user_png', upload_to='users/')),
                ('descripcion', models.TextField(blank=True, max_length=150, null=True)),
                ('servicios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.tservicio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
