# Generated by Django 4.2 on 2023-05-23 17:17

import applications.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_profile_servicios_profile_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='users/user_default_profile.png', upload_to=applications.users.models.user_directory_path_profile),
        ),
    ]
