# Generated by Django 4.2 on 2023-05-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='servicios',
            field=models.ManyToManyField(related_name='servicios', to='users.tservicio', verbose_name='Tipos de servicios'),
        ),
    ]
