# Generated by Django 4.2 on 2023-05-24 16:20

import applications.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='descripcion',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='users/user_default_profile.png', upload_to=applications.users.models.user_directory_path_profile),
        ),
    ]
