# Generated by Django 4.2 on 2023-05-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_profile_descripcion_alter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tservicio',
            name='informacion',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='tservicio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
