# Generated by Django 4.2 on 2023-05-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_tservicio_informacion_alter_tservicio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tservicio',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
