# Generated by Django 4.2 on 2023-05-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_tservicio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tservicio',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
