# Generated by Django 4.2 on 2023-05-24 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_tservicio_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tservicio',
            options={'ordering': ['id'], 'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
    ]
