# Generated by Django 4.2 on 2023-05-28 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_profile_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
