# Generated by Django 4.2 on 2023-05-29 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_categoria'),
        ('users', '0037_delete_profile'),
    ]

    operations = [
    ]
