# Generated by Django 4.2.1 on 2023-06-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_user_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DiaReserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaReserva', models.DateField()),
                ('horaReserva', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reservaEstado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horas', models.TimeField()),
            ],
        ),
    ]
