# Generated by Django 4.2 on 2023-05-29 19:56

import applications.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_alter_user_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='users/perfil_defecto.jpg', upload_to=applications.users.models.user_directory_path_profile),
        ),
    ]
