# Generated by Django 4.2 on 2023-05-30 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_colaboradores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colaboradores',
        ),
    ]
