# Generated by Django 4.2 on 2023-06-02 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_calificacion_diareserva_estadoreserva_hora'),
        ('users', '0044_delete_colaboradores'),
    ]

    operations = [
    ]
