# Generated by Django 4.2 on 2023-06-02 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_alter_user_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='MascotaFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_mascota', models.CharField(blank=True, max_length=50, null=True)),
                ('chip', models.BooleanField(default=False, verbose_name='Chip')),
                ('n_chip', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mascotas', verbose_name='Imagen del la Mascota')),
                ('descripccion', models.TextField(verbose_name='Descripccion del la mascota')),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dueño', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mascota',
                'verbose_name_plural': 'mascotas',
                'ordering': ['id'],
            },
        ),
    ]
