# Generated by Django 4.2 on 2023-06-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_especies_mascotaficha_especies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especies',
            name='informacion',
        ),
    ]
