# Generated by Django 3.2.8 on 2023-06-06 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_remove_especies_informacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascotaficha',
            old_name='dueno',
            new_name='user',
        ),
    ]
