# Generated by Django 3.2.8 on 2023-06-06 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_mascotaficha_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotaficha',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dueño', to=settings.AUTH_USER_MODEL),
        ),
    ]
