# Generated by Django 3.2.8 on 2023-06-06 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_alter_mascotaficha_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotaficha',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Dueño', to='users.user'),
            preserve_default=False,
        ),
    ]
