# Generated by Django 3.2.8 on 2023-06-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_auto_20230607_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diareserva',
            old_name='horaReserva',
            new_name='horaInicio',
        ),
    ]
