# Generated by Django 3.2.8 on 2023-06-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_rename_horareserva_diareserva_horainicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='diareserva',
            name='horaFin',
            field=models.TimeField(null=True),
        ),
    ]
