# Generated by Django 3.2.8 on 2023-06-07 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_diareserva_horafin'),
    ]

    operations = [
        migrations.AddField(
            model_name='diareserva',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado', to='users.estadoreserva'),
        ),
        migrations.AlterField(
            model_name='diareserva',
            name='horaFin',
            field=models.TimeField(null=True, verbose_name='fin'),
        ),
        migrations.AlterField(
            model_name='diareserva',
            name='horaInicio',
            field=models.TimeField(verbose_name='inicio'),
        ),
    ]
