# Generated by Django 3.2.19 on 2023-06-09 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_merge_20230603_2108'),
        ('users', '0060_auto_20230608_1323'),
    ]

    operations = [
    ]
