# Generated by Django 4.2.2 on 2023-06-11 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0061_merge_20230608_2218"),
        ("users", "0061_merge_20230609_1648"),
    ]

    operations = []
