# Generated by Django 3.2.8 on 2023-06-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_estadoreserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horaInicio', models.TimeField(verbose_name='inicio')),
                ('horaFin', models.TimeField(null=True, verbose_name='fin')),
            ],
        ),
    ]
