# Generated by Django 3.2.8 on 2023-06-12 21:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaReserva', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Dia')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado', to='users.estadoreserva')),
                ('horas', models.ManyToManyField(related_name='horas', to='users.Hora', verbose_name='Horas a seleccionar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cronograma', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
