# Generated by Django 3.2.8 on 2023-06-12 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_cronograma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronograma',
            name='estado',
        ),
        migrations.AddField(
            model_name='hora',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado', to='users.estadoreserva'),
        ),
    ]
