# Generated by Django 3.2.8 on 2023-06-12 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_auto_20230612_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hora',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado', to='users.estadoreserva'),
        ),
    ]
