# Generated by Django 3.2.8 on 2023-06-12 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_alter_hora_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronograma', to=settings.AUTH_USER_MODEL),
        ),
    ]
