# Generated by Django 3.2.8 on 2023-06-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='chip',
            field=models.CharField(choices=[('No', 'No'), ('Si', 'Si')], default='NO', max_length=2, verbose_name='Chip'),
        ),
    ]
