# Generated by Django 3.2.8 on 2023-06-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_alter_mascota_chip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='n_chip',
            field=models.CharField(blank=True, default='No poose', max_length=50, null=True),
        ),
    ]
