# Generated by Django 3.2.8 on 2023-06-14 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_alter_mascota_n_chip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hora',
            name='estado',
        ),
        migrations.AddField(
            model_name='cronograma',
            name='estado',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Estado', to='users.estadoreserva'),
        ),
        migrations.RemoveField(
            model_name='cronograma',
            name='horas',
        ),
        migrations.AddField(
            model_name='cronograma',
            name='horas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horas', to='users.hora', verbose_name='Horas a seleccionar'),
        ),
    ]
