# Generated by Django 3.2.8 on 2023-06-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_user_tipodeusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaCliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idCuidador', models.IntegerField(blank=True, null=True, unique=True)),
                ('cuidador', models.CharField(blank=True, max_length=16, null=True)),
                ('idCliente', models.IntegerField(blank=True, null=True, unique=True)),
                ('cliente', models.CharField(blank=True, max_length=16, null=True)),
                ('idReserva', models.IntegerField(blank=True, null=True, unique=True)),
                ('fechaReserva', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
