# Generated by Django 3.2.8 on 2023-06-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_user_promediocalificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipodeusuario',
            field=models.CharField(choices=[('1', 'Administrador'), ('2', 'Cliente'), ('3', 'Cuidador')], max_length=2, null=True),
        ),
    ]
