# Generated by Django 3.2.8 on 2023-06-15 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_auto_20230614_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacliente',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='reservacliente',
            name='cuidador',
        ),
        migrations.RemoveField(
            model_name='reservacliente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reservacliente',
            name='fechaReserva',
        ),
        migrations.RemoveField(
            model_name='reservacliente',
            name='idCliente',
        ),
        migrations.RemoveField(
            model_name='reservacliente',
            name='idCuidador',
        ),
        migrations.RemoveField(
            model_name='reservacliente',
            name='idReserva',
        ),
        migrations.AddField(
            model_name='reservacliente',
            name='cronograma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reservar', to='users.cronograma'),
        ),
        migrations.AddField(
            model_name='reservacliente',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='categoria',
            field=models.CharField(choices=[('1', 'Cliente'), ('2', 'Cuidador'), ('3', 'Administrador')], default=1, max_length=2, null=True),
        ),
    ]
