# Generated by Django 3.2.8 on 2023-06-15 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_auto_20230615_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacliente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reservacliente',
            name='fechaReserva',
        ),
        migrations.RemoveField(
            model_name='reservacliente',
            name='idCliente',
        ),
        migrations.RemoveField(
            model_name='reservacliente',
            name='idCuidador',
        ),
        migrations.RemoveField(
            model_name='reservacliente',
            name='idReserva',
        ),
        migrations.AlterField(
            model_name='reservacliente',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservacliente',
            name='cuidador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cuidador', to='users.cronograma'),
        ),
    ]
