# Generated by Django 3.2.8 on 2023-06-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0087_auto_20230615_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacliente',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='reservacliente',
            name='cuidador',
        ),
        migrations.AddField(
            model_name='reservacliente',
            name='correocliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservacliente',
            name='correocuidaor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservacliente',
            name='fechareserva',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservacliente',
            name='horasFin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservacliente',
            name='horasInicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservacliente',
            name='idCliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservacliente',
            name='idCuidador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservacliente',
            name='nombreCliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservacliente',
            name='nombreCuidador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
