# Generated by Django 4.2.2 on 2023-06-17 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0088_auto_20230616_1426"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservacliente",
            name="idCronograma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas",
                to="users.cronograma",
            ),
        ),
    ]
