# Generated by Django 3.2.8 on 2023-06-18 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_reservacliente_idcronograma'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacliente',
            name='clienteusername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
