# Generated by Django 3.2.8 on 2023-06-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0090_reservacliente_clienteusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacliente',
            name='servicios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
