# Generated by Django 4.2.2 on 2023-06-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0090_reservacliente_clienteusername"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservacliente",
            name="calificacion",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
