# Generated by Django 3.2.8 on 2023-06-22 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0094_alter_profile_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='region',
        ),
        migrations.AddField(
            model_name='user',
            name='comuna',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comuna', to='users.comuna'),
        ),
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(max_length=100, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Region', to='users.region'),
        ),
    ]
