# Generated by Django 3.2.8 on 2023-06-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0091_reservacliente_calificacion'),
        ('users', '0095_auto_20230622_1047'),
    ]

    operations = [
    ]
