# Generated by Django 4.2.2 on 2023-06-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0096_merge_20230622_1201"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Calificacion",
        ),
        migrations.AlterField(
            model_name="reservacliente",
            name="calificacion",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="promediocalificacion",
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
