# Generated by Django 3.2.8 on 2023-06-23 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0096_merge_20230622_2154'),
        ('users', '0097_delete_calificacion_and_more'),
    ]

    operations = [
    ]
