# Generated by Django 3.2.8 on 2023-06-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0098_merge_20230622_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='promediocalificacion',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, null=True),
        ),
    ]
