# Generated by Django 3.2.8 on 2023-06-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0099_alter_user_promediocalificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='descripcion',
            field=models.TextField(blank=True, default='Ingresa una descripcion', max_length=2000, null=True),
        ),
    ]
